version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - gradstat-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - WORKER_URL=http://worker:8001
      - PORT=3001
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - backend-uploads:/srv/uploads
      - backend-results:/srv/results
    depends_on:
      - worker
    networks:
      - gradstat-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - WORKER_PORT=8001
      - LOG_LEVEL=info
    volumes:
      - worker-temp:/worker/temp
      - worker-output:/worker/output
    networks:
      - gradstat-network

networks:
  gradstat-network:
    driver: bridge

volumes:
  backend-uploads:
  backend-results:
  worker-temp:
  worker-output:
