apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradstat-frontend
  labels:
    app: gradstat
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gradstat
      component: frontend
  template:
    metadata:
      labels:
        app: gradstat
        component: frontend
    spec:
      containers:
      - name: frontend
        image: gradstat-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradstat-backend
  labels:
    app: gradstat
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gradstat
      component: backend
  template:
    metadata:
      labels:
        app: gradstat
        component: backend
    spec:
      containers:
      - name: backend
        image: gradstat-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: WORKER_URL
          value: "http://gradstat-worker:8001"
        - name: PORT
          value: "3001"
        - name: ALLOWED_ORIGINS
          value: "https://gradstat.example.com"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradstat-worker
  labels:
    app: gradstat
    component: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gradstat
      component: worker
  template:
    metadata:
      labels:
        app: gradstat
        component: worker
    spec:
      containers:
      - name: worker
        image: gradstat-worker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: WORKER_PORT
          value: "8001"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
